"use client";

/**
 * Rush Mode — Fast-Track Resume Rewriter
 *
 * Single-page flow: paste resume + target job → get rewritten resume in ~30s.
 * Crucible rules: only uses facts from original resume, never fabricates.
 * Lives in (forge) route group — gets ForgeLayout wrapper (exit button, t.ROY, contact Troy).
 * No auth required. IP-rate-limited via /api/rush-resume.
 */

import { useState, useRef, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useForgeSession } from "@/lib/forge-context";
import { getOpusMessage } from "@/lib/opus-messages";
import { GhostGuide, TBtn } from "@crucible/consumer-ui";

type Step = "input" | "processing" | "result";

interface RushBullet {
  text: string;
  original: string;
}

interface RushResult {
  summary: string;
  bullets: RushBullet[];
  skills: string[];
  tips: string;
}

const PROCESSING_MESSAGES = [
  "Reading your resume...",
  "Identifying your strengths...",
  "Rewriting for the target role...",
  "Polishing the final draft...",
];

const ACCEPTED_TYPES = [
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/msword",
  "text/plain",
].join(",");

export default function RushPage() {
  const router = useRouter();
  const { session, updateSession } = useForgeSession();
  const audience = session.audience || "client";
  const isDemo = session.isDemo === true;
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    updateSession({ lastPageVisited: "rush" });
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const [step, setStep] = useState<Step>("input");
  const [resumeText, setResumeText] = useState("");
  const [targetJob, setTargetJob] = useState("");
  const [targetCompany, setTargetCompany] = useState("");
  const [jobDescription, setJobDescription] = useState("");
  const [error, setError] = useState("");
  const [result, setResult] = useState<RushResult | null>(null);
  const [uploading, setUploading] = useState(false);
  const [processingMsg, setProcessingMsg] = useState(0);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  async function handleFileUpload(file: File) {
    setUploading(true);
    setError("");
    try {
      const formData = new FormData();
      formData.append("file", file);
      const res = await fetch("/api/parse", { method: "POST", body: formData });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Could not read that file.");
      }
      const data = await res.json();
      setResumeText(data.resumeText || "");
    } catch (err: any) {
      setError(err.message || "File upload failed. Try pasting instead.");
    } finally {
      setUploading(false);
    }
  }

  async function handleSubmit() {
    if (!resumeText.trim() || !targetJob.trim()) return;

    setStep("processing");
    setError("");
    setProcessingMsg(0);

    const msgInterval = setInterval(() => {
      setProcessingMsg((prev) =>
        prev < PROCESSING_MESSAGES.length - 1 ? prev + 1 : prev
      );
    }, 6000);

    try {
      const res = await fetch("/api/rush-resume", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          resumeText: resumeText.trim(),
          targetJob: targetJob.trim(),
          targetCompany: targetCompany.trim() || undefined,
          jobDescription: jobDescription.trim() || undefined,
        }),
      });

      clearInterval(msgInterval);

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Something went wrong.");
      }

      const data = await res.json();
      setResult(data);
      setStep("result");
    } catch (err: any) {
      clearInterval(msgInterval);
      setError(err.message || "Something went wrong. Try again.");
      setStep("input");
    }
  }

  function buildResumeText() {
    if (!result) return "";
    const lines: string[] = [
      "PROFESSIONAL SUMMARY",
      "",
      result.summary,
      "",
      "EXPERIENCE",
      "",
    ];
    for (const b of result.bullets ?? []) {
      lines.push(`- ${b.text}`);
    }
    if (result.skills?.length) {
      lines.push("", "SKILLS", "", result.skills.join(" | "));
    }
    lines.push("", "", "Generated by Rush Mode — steelmanresumes.com");
    return lines.join("\n");
  }

  async function handleDownloadDocx() {
    if (!result) return;
    setDownloading(true);
    try {
      const res = await fetch("/api/forge/download", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          content: buildResumeText(),
          type: "resume",
          format: "docx",
        }),
      });
      if (!res.ok) throw new Error("Download failed");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "Rush_Resume_SteelMan.docx";
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      // Fallback to txt
      handleDownloadTxt();
    } finally {
      setDownloading(false);
    }
  }

  function handleDownloadTxt() {
    const text = buildResumeText();
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "Rush_Resume_SteelMan.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleCopy() {
    if (!result) return;
    const text = [
      result.summary,
      "",
      ...(result.bullets ?? []).map((b) => `• ${b.text}`),
      "",
      `Skills: ${(result.skills ?? []).join(", ")}`,
    ].join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  // --- INPUT STEP ---
  if (step === "input") {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center px-4 py-8 bg-t-bg">
        <div className="w-full max-w-lg">
          <div className="text-center mb-6">
            <h1 className="text-2xl font-bold text-t-white mb-2">
              Rush Resume
            </h1>
            <p className="text-base text-t-phos">
              Get a resume out the door in 60 seconds.
            </p>
          </div>

          {/* Disclaimer */}
          <div className="bg-t-panel px-4 py-3 mb-6 border border-t-line">
            <p className="text-sm text-t-phos leading-relaxed">
              <span className="font-semibold text-t-amber-bright">Straight up:</span> Rush Mode
              gives you the weakest possible version of your resume &mdash;
              just enough to submit an application today. It won&apos;t prepare
              you for the interview. For that, use{" "}
              <button
                onClick={() => router.push("/intro")}
                className="text-t-amber-bright underline underline-offset-2 hover:text-t-amber font-medium"
              >
                The Forge
              </button>
              .
            </p>
          </div>

          <GhostGuide
            message={getOpusMessage("rush", audience, isDemo)}
            pageId="rush"
          />

          {error && (
            <div className="bg-t-panel px-4 py-3 mb-4 border border-t-red">
              <p className="text-sm text-t-red">{error}</p>
            </div>
          )}

          {/* Resume input */}
          <div className="mb-4">
            <label className="block text-sm font-medium text-t-white mb-1">
              Your current resume
            </label>
            <textarea
              value={resumeText}
              onChange={(e) => setResumeText(e.target.value)}
              placeholder="Paste your resume text here..."
              rows={8}
              className="w-full px-4 py-3 border border-t-line text-sm bg-t-panel text-t-white focus:border-t-amber focus:outline-none transition-colors resize-none"
            />
            <div className="flex items-center gap-3 mt-2">
              <span className="text-xs text-t-phos-dim">or</span>
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                disabled={uploading}
                className="text-xs text-t-amber-bright hover:text-t-amber underline underline-offset-2"
              >
                {uploading ? "Reading file..." : "Upload a file (PDF, DOCX, TXT)"}
              </button>
              <input
                ref={fileInputRef}
                type="file"
                accept={ACCEPTED_TYPES}
                className="hidden"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) handleFileUpload(file);
                }}
              />
              {uploading && (
                <div className="w-4 h-4 border-2 border-t-amber border-t-transparent animate-spin" />
              )}
            </div>
          </div>

          {/* Target job */}
          <div className="mb-3">
            <label className="block text-sm font-medium text-t-white mb-1">
              Target job title <span className="text-t-red">*</span>
            </label>
            <input
              type="text"
              value={targetJob}
              onChange={(e) => setTargetJob(e.target.value)}
              placeholder='e.g., "Warehouse Associate" or "Customer Service Rep"'
              className="w-full px-4 py-3 border border-t-line text-sm bg-t-panel text-t-white focus:border-t-amber focus:outline-none transition-colors min-h-touch"
            />
          </div>

          {/* Target company (optional) */}
          <div className="mb-4">
            <label className="block text-sm font-medium text-t-white mb-1">
              Target company{" "}
              <span className="text-xs text-t-phos-dim font-normal">(optional)</span>
            </label>
            <input
              type="text"
              value={targetCompany}
              onChange={(e) => setTargetCompany(e.target.value)}
              placeholder='e.g., "Amazon" or "local restaurant"'
              className="w-full px-4 py-3 border border-t-line text-sm bg-t-panel text-t-white focus:border-t-amber focus:outline-none transition-colors min-h-touch"
            />
          </div>

          {/* Job description (optional) */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-t-white mb-1">
              Paste the job description{" "}
              <span className="text-xs text-t-phos-dim font-normal">(optional — makes it way better)</span>
            </label>
            <textarea
              value={jobDescription}
              onChange={(e) => setJobDescription(e.target.value)}
              placeholder="Copy and paste the job posting here. The AI will tailor your resume to match what they're looking for."
              rows={5}
              className="w-full px-4 py-3 border border-t-line text-sm bg-t-panel text-t-white focus:border-t-amber focus:outline-none transition-colors resize-none"
            />
          </div>

          <TBtn
            onClick={handleSubmit}
            disabled={!resumeText.trim() || !targetJob.trim()}
            className="w-full text-lg"
          >
            build my resume
          </TBtn>
        </div>
      </div>
    );
  }

  // --- PROCESSING STEP ---
  if (step === "processing") {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center px-4 bg-t-bg">
        <div className="w-full max-w-md text-center">
          <div className="w-16 h-16 mx-auto mb-6 relative">
            <div className="absolute inset-0 border-4 border-t-line" />
            <div className="absolute inset-0 border-4 border-t-amber border-t-transparent animate-spin" />
          </div>
          <h1 className="text-2xl font-bold mb-2 text-t-white">Building your resume</h1>
          <p className="text-base text-t-amber-bright transition-opacity duration-500">
            {PROCESSING_MESSAGES[processingMsg]}
          </p>
          <div className="w-full h-1.5 bg-t-line mt-8 overflow-hidden">
            <div
              className="h-full bg-t-amber transition-all duration-1000 ease-out"
              style={{
                width: `${Math.min(90, ((processingMsg + 1) / PROCESSING_MESSAGES.length) * 100)}%`,
              }}
            />
          </div>
        </div>
      </div>
    );
  }

  // --- RESULT STEP ---
  return (
    <div className="min-h-screen px-4 py-8 bg-t-bg">
      <div className="max-w-2xl mx-auto">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold text-t-white mb-2">
            Your Rush Resume
          </h1>
          <p className="text-sm text-t-phos-dim">
            For: {targetJob}
            {targetCompany ? ` at ${targetCompany}` : ""}
          </p>
        </div>

        {result && (
          <>
            {/* Professional Summary */}
            <section className="mb-6">
              <h2 className="text-lg font-bold text-t-white mb-2">
                Professional Summary
              </h2>
              <p className="text-base text-t-phos bg-t-panel p-5 border border-t-line leading-relaxed">
                {result.summary}
              </p>
            </section>

            {/* Experience Bullets */}
            <section className="mb-6">
              <h2 className="text-lg font-bold text-t-white mb-2">
                Experience
              </h2>
              <div className="space-y-3">
                {(result.bullets ?? []).map((b, i) => (
                  <div
                    key={i}
                    className="bg-t-panel p-4 border border-t-line"
                  >
                    <p className="text-sm text-t-white font-medium">
                      {b.text}
                    </p>
                    <p className="text-xs text-t-phos-dim mt-1 italic">
                      Based on: &ldquo;{b.original}&rdquo;
                    </p>
                  </div>
                ))}
              </div>
            </section>

            {/* Skills */}
            {result.skills.length > 0 && (
              <section className="mb-6">
                <h2 className="text-lg font-bold text-t-white mb-2">
                  Skills
                </h2>
                <div className="flex flex-wrap gap-2">
                  {result.skills.map((skill, i) => (
                    <span
                      key={i}
                      className="px-3 py-1.5 text-sm font-medium border border-t-line bg-t-panel-2 text-t-phos"
                    >
                      {skill}
                    </span>
                  ))}
                </div>
              </section>
            )}

            {/* Tip */}
            {result.tips && (
              <section className="mb-8">
                <div className="bg-t-panel p-4 border border-t-line">
                  <p className="text-sm text-t-phos">
                    <span className="font-medium text-t-amber-bright">Tip: </span>
                    {result.tips}
                  </p>
                </div>
              </section>
            )}

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-3 mb-4">
              <button
                onClick={handleDownloadDocx}
                disabled={downloading}
                className="t-focus flex-1 px-6 py-4 bg-t-amber text-white font-bold shadow-[0_3px_8px_rgba(22,26,21,0.15)] hover:bg-t-amber-bright disabled:opacity-40 disabled:shadow-none transition-colors min-h-touch"
              >
                {downloading ? "Preparing..." : "Download .docx"}
              </button>
              <button
                onClick={handleCopy}
                className="t-focus flex-1 px-6 py-4 bg-transparent border border-t-amber text-t-amber-bright font-bold hover:bg-t-amber/10 transition-colors min-h-touch"
              >
                {copied ? "Copied!" : "Copy Text"}
              </button>
              <button
                onClick={handleDownloadTxt}
                className="t-focus flex-1 px-6 py-4 bg-transparent border border-t-line text-t-phos-dim font-bold hover:text-t-white hover:border-t-phos-dim transition-colors min-h-touch"
              >
                Download .txt
              </button>
            </div>

            {/* Continue editing in the Application Tailor */}
            <button
              onClick={() => {
                try {
                  sessionStorage.setItem("rush_result", JSON.stringify(result));
                  sessionStorage.setItem("rush_target", targetJob);
                } catch {}
                router.push("/dashboard/application-tailor?from=rush");
              }}
              className="t-focus w-full px-6 py-3 bg-transparent border border-t-line text-t-phos text-sm font-medium hover:border-t-phos-dim hover:text-t-white transition-colors mb-4"
            >
              Continue editing in the Application Tailor
            </button>

            {/* Interview Warning */}
            <div className="bg-t-panel px-4 py-3 mb-6 border border-t-line">
              <p className="text-sm text-t-phos leading-relaxed">
                <span className="font-semibold text-t-amber-bright">This gets you in the door, not through the interview.</span>{" "}
                Rush Mode rewrites what you gave it — nothing more. It doesn&apos;t
                know your strengths, your story, or what makes you different.
                An interviewer will ask about all of that.
              </p>
            </div>

            {/* Save + Go Deeper CTA */}
            <div className="bg-t-panel-2 p-6 border border-t-amber text-center">
              <h3 className="font-bold text-t-white mb-2">
                Ready to actually prepare?
              </h3>
              <p className="text-sm text-t-phos-dim leading-relaxed mb-4">
                The Forge builds your real narrative — strengths, career paths,
                resources for your situation, and documents that hold up in an
                interview. Takes about 10 minutes.
              </p>
              <TBtn
                onClick={() => {
                  updateSession({
                    resumeText,
                    resumeMethod: "rush",
                    pagesVisited: ["rush"],
                  });
                  router.push("/welcome");
                }}
                className="text-lg"
              >
                go to The Forge
              </TBtn>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
