"use client";

/**
 * Rush Mode — Fast-Track Resume Rewriter
 *
 * Single-page flow: paste resume + target job → get rewritten resume in ~30s.
 * Crucible rules: only uses facts from original resume, never fabricates.
 * Lives in (forge) route group — gets ForgeLayout wrapper (exit button, Opus, contact Troy).
 * No auth required. IP-rate-limited via /api/rush-resume.
 */

import { useState, useRef } from "react";
import { useRouter } from "next/navigation";

type Step = "input" | "processing" | "result";

interface RushBullet {
  text: string;
  original: string;
}

interface RushResult {
  summary: string;
  bullets: RushBullet[];
  skills: string[];
  tips: string;
}

const PROCESSING_MESSAGES = [
  "Reading your resume...",
  "Identifying your strengths...",
  "Rewriting for the target role...",
  "Polishing the final draft...",
];

const ACCEPTED_TYPES = [
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/msword",
  "text/plain",
].join(",");

export default function RushPage() {
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [step, setStep] = useState<Step>("input");
  const [resumeText, setResumeText] = useState("");
  const [targetJob, setTargetJob] = useState("");
  const [targetCompany, setTargetCompany] = useState("");
  const [error, setError] = useState("");
  const [result, setResult] = useState<RushResult | null>(null);
  const [uploading, setUploading] = useState(false);
  const [processingMsg, setProcessingMsg] = useState(0);
  const [copied, setCopied] = useState(false);

  async function handleFileUpload(file: File) {
    setUploading(true);
    setError("");
    try {
      const formData = new FormData();
      formData.append("file", file);
      const res = await fetch("/api/parse", { method: "POST", body: formData });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Could not read that file.");
      }
      const data = await res.json();
      setResumeText(data.resumeText || "");
    } catch (err: any) {
      setError(err.message || "File upload failed. Try pasting instead.");
    } finally {
      setUploading(false);
    }
  }

  async function handleSubmit() {
    if (!resumeText.trim() || !targetJob.trim()) return;

    setStep("processing");
    setError("");
    setProcessingMsg(0);

    const msgInterval = setInterval(() => {
      setProcessingMsg((prev) =>
        prev < PROCESSING_MESSAGES.length - 1 ? prev + 1 : prev
      );
    }, 6000);

    try {
      const res = await fetch("/api/rush-resume", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          resumeText: resumeText.trim(),
          targetJob: targetJob.trim(),
          targetCompany: targetCompany.trim() || undefined,
        }),
      });

      clearInterval(msgInterval);

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Something went wrong.");
      }

      const data = await res.json();
      setResult(data);
      setStep("result");
    } catch (err: any) {
      clearInterval(msgInterval);
      setError(err.message || "Something went wrong. Try again.");
      setStep("input");
    }
  }

  function handleDownload() {
    if (!result) return;
    const lines: string[] = [
      "═══════════════════════════════════════",
      "  RUSH RESUME — Steel Man Resumes",
      "═══════════════════════════════════════",
      "",
      `Target: ${targetJob}${targetCompany ? ` at ${targetCompany}` : ""}`,
      "",
      "PROFESSIONAL SUMMARY",
      "────────────────────",
      result.summary,
      "",
      "EXPERIENCE",
      "──────────",
    ];
    for (const b of result.bullets) {
      lines.push(`• ${b.text}`);
    }
    if (result.skills.length) {
      lines.push("", "SKILLS", "──────", result.skills.join(", "));
    }
    if (result.tips) {
      lines.push("", "TIP", "───", result.tips);
    }
    lines.push("", "", "Generated by Rush Mode — steelmanresumes.com");
    lines.push("For deeper work, try The Forge → steelmanresumes.com/intro");

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "rush-resume.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleCopy() {
    if (!result) return;
    const text = [
      result.summary,
      "",
      ...result.bullets.map((b) => `• ${b.text}`),
      "",
      `Skills: ${result.skills.join(", ")}`,
    ].join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  // --- INPUT STEP ---
  if (step === "input") {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center px-4 py-8">
        <div className="w-full max-w-lg">
          <div className="text-center mb-8">
            <h1 className="text-2xl font-bold text-foreground mb-2">
              Rush Resume
            </h1>
            <p className="text-body text-foreground">
              Get a job-ready resume in 60 seconds.
            </p>
            <p className="text-sm text-muted mt-2">
              This is a fast start. For real interview confidence, come back for{" "}
              <button
                onClick={() => router.push("/intro")}
                className="text-sage-600 underline underline-offset-2 hover:text-sage-700"
              >
                The Forge
              </button>
              .
            </p>
          </div>

          {error && (
            <div className="bg-red-50 rounded-xl px-4 py-3 mb-4 border border-red-200">
              <p className="text-sm text-red-700">{error}</p>
            </div>
          )}

          {/* Resume input */}
          <div className="mb-4">
            <label className="block text-sm font-medium text-foreground mb-1">
              Your current resume
            </label>
            <textarea
              value={resumeText}
              onChange={(e) => setResumeText(e.target.value)}
              placeholder="Paste your resume text here..."
              rows={8}
              className="w-full px-4 py-3 rounded-xl border-2 border-border text-sm bg-white focus:border-sage-600 transition-colors resize-none"
            />
            <div className="flex items-center gap-3 mt-2">
              <span className="text-xs text-muted">or</span>
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                disabled={uploading}
                className="text-xs text-sage-600 hover:text-sage-700 underline underline-offset-2"
              >
                {uploading ? "Reading file..." : "Upload a file (PDF, DOCX, TXT)"}
              </button>
              <input
                ref={fileInputRef}
                type="file"
                accept={ACCEPTED_TYPES}
                className="hidden"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) handleFileUpload(file);
                }}
              />
              {uploading && (
                <div className="w-4 h-4 border-2 border-sage-600 border-t-transparent rounded-full animate-spin" />
              )}
            </div>
          </div>

          {/* Target job */}
          <div className="mb-3">
            <label className="block text-sm font-medium text-foreground mb-1">
              Target job title <span className="text-red-400">*</span>
            </label>
            <input
              type="text"
              value={targetJob}
              onChange={(e) => setTargetJob(e.target.value)}
              placeholder='e.g., "Warehouse Associate" or "Customer Service Rep"'
              className="w-full px-4 py-3 rounded-xl border-2 border-border text-sm bg-white focus:border-sage-600 transition-colors min-h-touch"
            />
          </div>

          {/* Target company (optional) */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-foreground mb-1">
              Target company{" "}
              <span className="text-xs text-muted font-normal">(optional)</span>
            </label>
            <input
              type="text"
              value={targetCompany}
              onChange={(e) => setTargetCompany(e.target.value)}
              placeholder='e.g., "Amazon" or "local restaurant"'
              className="w-full px-4 py-3 rounded-xl border-2 border-border text-sm bg-white focus:border-sage-600 transition-colors min-h-touch"
            />
          </div>

          <button
            onClick={handleSubmit}
            disabled={!resumeText.trim() || !targetJob.trim()}
            className="w-full px-6 py-4 bg-sage-600 text-white rounded-xl font-medium hover:bg-sage-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors min-h-touch text-lg"
          >
            Build My Resume
          </button>
        </div>
      </div>
    );
  }

  // --- PROCESSING STEP ---
  if (step === "processing") {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center px-4">
        <div className="w-full max-w-md text-center">
          <div className="w-16 h-16 mx-auto mb-6 relative">
            <div className="absolute inset-0 border-4 border-sage-200 rounded-full" />
            <div className="absolute inset-0 border-4 border-sage-600 rounded-full border-t-transparent animate-spin" />
          </div>
          <h1 className="text-2xl font-bold mb-2">Building your resume</h1>
          <p className="text-body text-sage-600 transition-opacity duration-500">
            {PROCESSING_MESSAGES[processingMsg]}
          </p>
          <div className="w-full h-1.5 bg-sage-100 rounded-full mt-8 overflow-hidden">
            <div
              className="h-full bg-sage-500 rounded-full transition-all duration-1000 ease-out"
              style={{
                width: `${Math.min(90, ((processingMsg + 1) / PROCESSING_MESSAGES.length) * 100)}%`,
              }}
            />
          </div>
        </div>
      </div>
    );
  }

  // --- RESULT STEP ---
  return (
    <div className="min-h-screen px-4 py-8">
      <div className="max-w-2xl mx-auto">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold text-foreground mb-2">
            Your Rush Resume
          </h1>
          <p className="text-sm text-muted">
            For: {targetJob}
            {targetCompany ? ` at ${targetCompany}` : ""}
          </p>
        </div>

        {result && (
          <>
            {/* Professional Summary */}
            <section className="mb-6">
              <h2 className="text-lg font-bold text-foreground mb-2">
                Professional Summary
              </h2>
              <p className="text-body text-foreground bg-sage-50 rounded-xl p-5 border border-sage-200 leading-relaxed">
                {result.summary}
              </p>
            </section>

            {/* Experience Bullets */}
            <section className="mb-6">
              <h2 className="text-lg font-bold text-foreground mb-2">
                Experience
              </h2>
              <div className="space-y-3">
                {result.bullets.map((b, i) => (
                  <div
                    key={i}
                    className="bg-white rounded-xl p-4 border border-border"
                  >
                    <p className="text-sm text-foreground font-medium">
                      {b.text}
                    </p>
                    <p className="text-xs text-muted mt-1 italic">
                      Based on: &ldquo;{b.original}&rdquo;
                    </p>
                  </div>
                ))}
              </div>
            </section>

            {/* Skills */}
            {result.skills.length > 0 && (
              <section className="mb-6">
                <h2 className="text-lg font-bold text-foreground mb-2">
                  Skills
                </h2>
                <div className="flex flex-wrap gap-2">
                  {result.skills.map((skill, i) => (
                    <span
                      key={i}
                      className="px-3 py-1.5 rounded-lg text-sm font-medium bg-sage-100 text-sage-700"
                    >
                      {skill}
                    </span>
                  ))}
                </div>
              </section>
            )}

            {/* Tip */}
            {result.tips && (
              <section className="mb-8">
                <div className="bg-warm-50 rounded-xl p-4 border border-warm-200">
                  <p className="text-sm text-earth-700">
                    <span className="font-medium">Tip: </span>
                    {result.tips}
                  </p>
                </div>
              </section>
            )}

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-3 mb-8">
              <button
                onClick={handleDownload}
                className="flex-1 px-6 py-4 bg-white border-2 border-sage-600 text-sage-600 rounded-xl font-medium hover:bg-sage-50 transition-colors min-h-touch"
              >
                Download
              </button>
              <button
                onClick={handleCopy}
                className="flex-1 px-6 py-4 bg-white border-2 border-sage-600 text-sage-600 rounded-xl font-medium hover:bg-sage-50 transition-colors min-h-touch"
              >
                {copied ? "Copied!" : "Copy to Clipboard"}
              </button>
              <button
                onClick={() => router.push("/intro")}
                className="flex-1 px-6 py-4 bg-sage-600 text-white rounded-xl font-medium hover:bg-sage-700 transition-colors min-h-touch"
              >
                Go Deeper
              </button>
            </div>

            {/* Caveat */}
            <div className="bg-warm-50 rounded-2xl p-6 border border-warm-200 text-center">
              <p className="text-sm text-earth-700 leading-relaxed">
                This is a quick job to get you moving. Real strength — the kind
                that wins interviews — takes time. Come back to{" "}
                <button
                  onClick={() => router.push("/intro")}
                  className="text-sage-600 underline underline-offset-2 hover:text-sage-700 font-medium"
                >
                  The Forge
                </button>{" "}
                when you&apos;re ready.
              </p>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
