#!/usr/bin/env node
/**
 * THE PACKAGER.
 *
 *   node build.mjs                 build both SCORM 1.2 and 2004 packages
 *   node build.mjs --scorm 1.2     build only 1.2
 *   node build.mjs --scorm 2004    build only 2004
 *
 * Three jobs, in this order, and it stops at the first failure:
 *
 *   1. GENERATE the manifest from the actual file list on disk. The single
 *      most common reason a SCORM package is rejected is a file that exists in
 *      the zip but is missing from the manifest. Hand-maintaining that list
 *      guarantees it happens eventually, so nothing here is hand-maintained.
 *
 *   2. PREFLIGHT every byte that is about to be zipped against the containment
 *      rules in preflight.mjs, and fail the build on any blocking finding. A
 *      package that can reach the network cannot be produced by this script.
 *
 *   3. ZIP with the manifest at the root, written by hand with node:zlib so
 *      the toolchain has no dependencies either. The other common rejection is
 *      zipping the containing folder instead of its contents. That is not
 *      possible here: entries are named from the file list, not from a path.
 *
 * The report written alongside the zip is a deliverable, not a build log. It
 * is the thing that goes to CypherWorx and to ViaPath with the package.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { join, relative, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";
import { deflateRawSync } from "node:zlib";
import { preflight, renderReport } from "./preflight.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "src");
const DIST = join(HERE, "dist");

/* ------------------------------------------------------------- identity */

/**
 * FORGE TABLET. Named by Troy 2026-09-11.
 *
 * The naming convention across the family is literal and descriptive: The
 * Forge and The Refinery on the web, Forge Tablet in a facility, and Refinery
 * Tablet if and when that one is built. A person in a facility and a vetting
 * reviewer reading a catalog listing should both be able to tell what it is
 * without being told.
 *
 * Everything a human sees is in this one object, so a rename is a one-line
 * change and a rebuild. PACKAGE_ID is the exception: it is what the LMS
 * stores, so once a package has been submitted for vetting it must not change.
 * A new identifier reads to an LMS as an unrelated course and disconnects
 * every learner record already attached to the old one.
 */
const BRAND = {
  PACKAGE_ID: "SMR_FORGE_TABLET",
  COURSE_TITLE: "Forge Tablet",
  ITEM_TITLE: "Forge Tablet",
  ORGANIZATION: "Steel Man Resumes",
  DESCRIPTION:
    "A short, offline career intake. Seven questions about what you are good at " +
    "and what you want next. Produces a code the learner carries out with them.",
  VERSION: "1.1",
  // Typical duration, ISO 8601. Used by some LMS catalogs for the course card.
  TYPICAL_DURATION: "PT10M"
};

/* ------------------------------------------------------------ file list */

/** Every file under src/, sorted, with forward-slash names for the zip. */
function collectFiles(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...collectFiles(full, base));
    else out.push({ path: full, name: relative(base, full).split("\\").join("/") });
  }
  return out;
}

/* -------------------------------------------------------------- manifest */

function xmlEscape(s) {
  return String(s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

function manifest12(files) {
  const fileLines = files.map((f) => `      <file href="${xmlEscape(f.name)}"/>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  SCORM 1.2 content package manifest.
  GENERATED by build.mjs from the contents of src/. Do not hand edit: the next
  build overwrites it, and a hand edit is how a file goes undeclared.
-->
<manifest identifier="${xmlEscape(BRAND.PACKAGE_ID)}_12" version="${xmlEscape(BRAND.VERSION)}"
  xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                      http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd
                      http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd">

  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>

  <organizations default="ORG">
    <organization identifier="ORG">
      <title>${xmlEscape(BRAND.COURSE_TITLE)}</title>
      <item identifier="ITEM" identifierref="RES" isvisible="true">
        <title>${xmlEscape(BRAND.ITEM_TITLE)}</title>
        <!--
          masteryscore 0: this is an intake, not an assessment. There is no
          score, nothing is graded, and no answer is wrong. Completion is the
          only outcome reported.
        -->
        <adlcp:masteryscore>0</adlcp:masteryscore>
        <adlcp:maxtimeallowed>04:00:00.00</adlcp:maxtimeallowed>
        <adlcp:datafromlms></adlcp:datafromlms>
      </item>
    </organization>
  </organizations>

  <resources>
    <resource identifier="RES" type="webcontent" adlcp:scormtype="sco" href="index.html">
${fileLines}
    </resource>
  </resources>
</manifest>
`;
}

function manifest2004(files) {
  const fileLines = files.map((f) => `      <file href="${xmlEscape(f.name)}"/>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  SCORM 2004 4th Edition content package manifest.
  GENERATED by build.mjs from the contents of src/. Do not hand edit.

  No imsss sequencing is declared. A single SCO with no prerequisites and no
  rollup rules is the simplest thing an LMS can host, and simple is the point.
-->
<manifest identifier="${xmlEscape(BRAND.PACKAGE_ID)}_2004" version="${xmlEscape(BRAND.VERSION)}"
  xmlns="http://www.imsglobal.org/xsd/imscp_v1p1"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3"
  xmlns:adlseq="http://www.adlnet.org/xsd/adlseq_v1p3"
  xmlns:adlnav="http://www.adlnet.org/xsd/adlnav_v1p3"
  xmlns:imsss="http://www.imsglobal.org/xsd/imsss"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 imscp_v1p1.xsd
                      http://www.adlnet.org/xsd/adlcp_v1p3 adlcp_v1p3.xsd
                      http://www.adlnet.org/xsd/adlseq_v1p3 adlseq_v1p3.xsd
                      http://www.adlnet.org/xsd/adlnav_v1p3 adlnav_v1p3.xsd
                      http://www.imsglobal.org/xsd/imsss imsss_v1p0.xsd">

  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>2004 4th Edition</schemaversion>
  </metadata>

  <organizations default="ORG">
    <organization identifier="ORG">
      <title>${xmlEscape(BRAND.COURSE_TITLE)}</title>
      <item identifier="ITEM" identifierref="RES">
        <title>${xmlEscape(BRAND.ITEM_TITLE)}</title>
        <adlcp:completionThreshold completedByMeasure="false"/>
        <adlcp:timeLimitAction>continue,no message</adlcp:timeLimitAction>
      </item>
    </organization>
  </organizations>

  <resources>
    <resource identifier="RES" type="webcontent" adlcp:scormType="sco" href="index.html">
${fileLines}
    </resource>
  </resources>
</manifest>
`;
}

/* ------------------------------------------------------------------- zip */

/**
 * A minimal, correct ZIP writer. Store or deflate, no directory entries, no
 * zip64. Written out rather than pulled in because the packaging step is part
 * of what gets audited, and 80 lines of visible format handling is a smaller
 * thing to explain than an archiver dependency.
 */
const CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

/**
 * @param {{name:string, data:Buffer}[]} entries
 * @param {Date} mtime Fixed timestamp so two builds of identical source
 *        produce byte-identical zips. A reviewer can then hash the zip itself
 *        and get the same answer we publish.
 */
function makeZip(entries, mtime) {
  const dosTime = ((mtime.getHours() << 11) | (mtime.getMinutes() << 5) | (mtime.getSeconds() >> 1)) & 0xffff;
  const dosDate = (((mtime.getFullYear() - 1980) << 9) | ((mtime.getMonth() + 1) << 5) | mtime.getDate()) & 0xffff;

  const locals = [];
  const centrals = [];
  let offset = 0;

  for (const entry of entries) {
    const nameBuf = Buffer.from(entry.name, "utf8");
    const raw = entry.data;
    const deflated = deflateRawSync(raw, { level: 9 });
    const useDeflate = deflated.length < raw.length;
    const body = useDeflate ? deflated : raw;
    const method = useDeflate ? 8 : 0;
    const crc = crc32(raw);

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);        // version needed
    local.writeUInt16LE(0x0800, 6);    // UTF-8 name flag
    local.writeUInt16LE(method, 8);
    local.writeUInt16LE(dosTime, 10);
    local.writeUInt16LE(dosDate, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(body.length, 18);
    local.writeUInt32LE(raw.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28);
    locals.push(local, nameBuf, body);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);      // version made by
    central.writeUInt16LE(20, 6);      // version needed
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(method, 10);
    central.writeUInt16LE(dosTime, 12);
    central.writeUInt16LE(dosDate, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(body.length, 20);
    central.writeUInt32LE(raw.length, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt32LE(0, 38);      // external attributes
    central.writeUInt32LE(offset, 42);
    centrals.push(central, nameBuf);

    offset += local.length + nameBuf.length + body.length;
  }

  const centralBuf = Buffer.concat(centrals);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBuf.length, 12);
  end.writeUInt32LE(offset, 16);

  return Buffer.concat([...locals, centralBuf, end]);
}

/* ------------------------------------------------------------------ build */

function buildOne(version, srcFiles, stamp) {
  const flag = version === "1.2" ? "1.2" : "2004";
  const suffix = version === "1.2" ? "scorm12" : "scorm2004";
  const outName = `${BRAND.PACKAGE_ID.toLowerCase()}-${suffix}-v${BRAND.VERSION}`;

  // The manifest is written to dist/ first so preflight scans the exact bytes
  // that go in the zip, not a copy of them.
  const staging = join(DIST, outName);
  rmSync(staging, { recursive: true, force: true });
  mkdirSync(staging, { recursive: true });

  const manifestXml = version === "1.2" ? manifest12(srcFiles) : manifest2004(srcFiles);
  const manifestPath = join(staging, "imsmanifest.xml");
  writeFileSync(manifestPath, manifestXml, "utf8");

  for (const f of srcFiles) {
    const dest = join(staging, f.name);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, readFileSync(f.path));
  }

  // imsmanifest.xml must be first in the archive as well as at the root. Some
  // older LMS importers read the first entry rather than searching.
  const zipFiles = [
    { path: manifestPath, name: "imsmanifest.xml" },
    ...srcFiles.map((f) => ({ path: join(staging, f.name), name: f.name }))
  ];

  const result = preflight(zipFiles);
  const report = renderReport(result, {
    title: BRAND.COURSE_TITLE,
    packageId: BRAND.PACKAGE_ID + (version === "1.2" ? "_12" : "_2004"),
    scormVersion: version === "1.2" ? "1.2" : "2004 4th Edition",
    scormFlag: flag,
    generatedAt: stamp.toISOString()
  });

  writeFileSync(join(DIST, outName + "-CONTAINMENT-REPORT.txt"), report, "utf8");

  if (!result.ok) {
    process.stdout.write(report);
    console.error(`\nBUILD FAILED for SCORM ${version}. Blocking findings above. No zip written.`);
    return { ok: false };
  }

  // Sanity check that has nothing to do with security and everything to do
  // with not getting bounced: every declared file exists, every present file
  // is declared. Both directions.
  const declared = new Set([...manifestXml.matchAll(/<file href="([^"]+)"/g)].map((m) => m[1]));
  const present = new Set(srcFiles.map((f) => f.name));
  for (const d of declared) {
    if (!present.has(d)) { console.error(`Manifest declares a missing file: ${d}`); return { ok: false }; }
  }
  for (const p of present) {
    if (!declared.has(p)) { console.error(`File is in the package but not declared: ${p}`); return { ok: false }; }
  }

  const zip = makeZip(
    zipFiles.map((f) => ({ name: f.name, data: readFileSync(f.path) })),
    stamp
  );
  const zipPath = join(DIST, outName + ".zip");
  writeFileSync(zipPath, zip);
  rmSync(staging, { recursive: true, force: true });

  return { ok: true, zipPath, bytes: zip.length, files: zipFiles.length, report };
}

/* ------------------------------------------------------------------- main */

function main() {
  const argv = process.argv.slice(2);
  const idx = argv.indexOf("--scorm");
  const want = idx >= 0 ? argv[idx + 1] : "both";
  const versions = want === "both" ? ["1.2", "2004"] : [want];

  for (const v of versions) {
    if (v !== "1.2" && v !== "2004") {
      console.error(`Unknown SCORM version "${v}". Use 1.2 or 2004.`);
      process.exit(2);
    }
  }

  if (!existsSync(SRC)) { console.error("No src/ directory."); process.exit(2); }
  mkdirSync(DIST, { recursive: true });

  const srcFiles = collectFiles(SRC);
  if (!srcFiles.some((f) => f.name === "index.html")) {
    console.error("src/index.html is required. It is the launch file named in the manifest.");
    process.exit(2);
  }

  // Fixed timestamp so the build is reproducible byte for byte.
  const stamp = new Date("2026-01-01T00:00:00Z");

  let failed = false;
  for (const v of versions) {
    const r = buildOne(v, srcFiles, stamp);
    if (!r.ok) { failed = true; continue; }
    console.log(`SCORM ${v.padEnd(4)}  PASS   ${String(r.bytes).padStart(7)} bytes  ${r.files} files  ${relative(HERE, r.zipPath)}`);
  }

  if (failed) process.exit(1);
  console.log(`\nContainment reports written to ${relative(process.cwd(), DIST)}/`);
  console.log("Next: upload a zip to SCORM Cloud, then record the offline run.");
}

main();
