/**
 * Resume mint check, deterministic layer: calibration and rule tests.
 * Fixture: a fictional person run through the Forge writer on a preview
 * deploy (2026-10-05). Every finding asserted here was a real defect in that
 * output. All people, employers and contacts are invented.
 *
 * Run: npm test  (node --import tsx --test, no extra deps)
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { runMintCheck } from "../resumeMintCheckShared";

const fx = JSON.parse(readFileSync(join(__dirname, "fixtures-mint-preview.json"), "utf8"));
const has = (r: ReturnType<typeof runMintCheck>, rule: string, sev: string, re: RegExp) =>
  r.findings.some((f) => f.rule === rule && f.severity === sev && re.test(f.line));

test("calibration: the preview output is not mint", () => {
  const r = runMintCheck({ output: fx.output, source: fx.source, kind: "resume" });
  assert.equal(r.passesDeterministic, false);
  assert.ok(has(r, "STD-F02", "BLOCK", /No formal education provided/), "empty education section printed as content");
  assert.ok(has(r, "STD-T07", "FIX", /High-Volume/i), "high-volume never said by the person");
  assert.ok(has(r, "STD-T01", "FIX", /Order Timing/), "competency the person never named");
});

const SRC = `Dana Example
Riverton, OH | 555-0188 | dana@example.com
Forklift Operator | Northgate Freight | 2019 - 2023
Moved 40 pallets a shift. Trained 3 new drivers.
Cashier | Corner Market | 2016 - 2019`;

const CLEAN = `DANA EXAMPLE
Riverton, OH | 555-0188 | dana@example.com

PROFESSIONAL EXPERIENCE
FORKLIFT OPERATOR | Northgate Freight | 2019 - 2023
- Moved 40 pallets a shift.
- Trained 3 new drivers.
CASHIER | Corner Market | 2016 - 2019

CORE COMPETENCIES
Forklift | Pallet Moving | Driver Training`;

test("a faithful page passes the deterministic layer", () => {
  const r = runMintCheck({ output: CLEAN, source: SRC, kind: "resume" });
  assert.deepEqual(r.findings, []);
  assert.equal(r.passesDeterministic, true);
});

test("STD-T05: a year not in the source blocks", () => {
  const r = runMintCheck({ output: CLEAN.replace("2016 - 2019", "2015 - 2019"), source: SRC });
  assert.ok(has(r, "STD-T05", "BLOCK", /2015/));
});

test("STD-T02: an added number blocks, a dropped number is a fix", () => {
  const r = runMintCheck({ output: CLEAN.replace("40 pallets", "60 pallets"), source: SRC, kind: "resume" });
  assert.ok(has(r, "STD-T02", "BLOCK", /60 pallets/));
  assert.ok(has(r, "STD-T02", "FIX", /40 pallets/));
});

test("STD-C05 and STD-C07: euphemism and legal status block unless the person said them", () => {
  const out = CLEAN + "\n\nCareer break 2014 - 2016. Record cleared.";
  const r = runMintCheck({ output: out, source: SRC + "\n2014 2016", kind: "resume" });
  assert.ok(has(r, "STD-C05", "BLOCK", /Career break/i));
  assert.ok(has(r, "STD-C07", "BLOCK", /Record cleared/i));
  const ok = runMintCheck({ output: out, source: SRC + "\nI took a career break 2014 - 2016. My record cleared.", kind: "resume" });
  assert.ok(!ok.findings.some((f) => f.rule === "STD-C05" || f.rule === "STD-C07"));
});

test("STD-F01: a job with no dates blocks", () => {
  const r = runMintCheck({ output: CLEAN.replace(" | 2016 - 2019", ""), source: SRC, kind: "resume" });
  assert.ok(has(r, "STD-F01", "BLOCK", /Corner Market/));
});

test("STD-F06 and STD-F05: tool marks and placeholders block", () => {
  const r = runMintCheck({ output: CLEAN + "\n\nGenerated by Rush Mode at steelmanresumes.com\n[Your Phone]", source: SRC, kind: "resume" });
  assert.ok(has(r, "STD-F06", "BLOCK", /Rush Mode/));
  assert.ok(has(r, "STD-F05", "BLOCK", /Your Phone/));
});

test("a cover letter keeps its two allowed placeholders", () => {
  const letter = "Dear [Hiring Manager],\n\nI moved 40 pallets a shift at Northgate Freight and want to do that at [Company Name].\n\nSincerely,\nDana Example";
  const r = runMintCheck({ output: letter, source: SRC, kind: "cover_letter" });
  assert.ok(!r.findings.some((f) => f.rule === "STD-F05"), JSON.stringify(r.findings));
});

test("STD-A02: dash punctuation is a fix", () => {
  const r = runMintCheck({ output: CLEAN.replace("- Moved 40 pallets a shift.", "- Moved 40 pallets a shift — every shift."), source: SRC, kind: "resume" });
  assert.ok(r.findings.some((f) => f.rule === "STD-A02"));
});
