/**
 * gen_readme — README Table of Contents (TXT)
 *
 * Consumes: artifact_manifest.v1
 * Template-based — no AI needed
 */
import { getRunData, uploadFile, insert, emitEvent } from '@crucible/core';
import type { ArtifactManifestV1 as ArtifactManifestV1Type } from '@crucible/core';
import type { ArtifactJobData, GeneratorResult } from './types';

export async function generateReadme(job: ArtifactJobData): Promise<GeneratorResult> {
  const { runId, bundleId, orgId, projectId, artifactKey } = job;

  let manifest: ArtifactManifestV1Type | null = null;
  try { manifest = await getRunData<ArtifactManifestV1Type>(runId, 'artifact_manifest.v1'); } catch { /* ok */ }

  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const ARTIFACT_DESCRIPTIONS: Record<string, string> = {
    'README — Table of Contents': 'This file. Overview of your career package.',
    'Quick Start Guide': 'Hour-by-hour guide for your first 48 hours.',
    'Resume': 'Your professionally formatted resume, ready to submit.',
    'Cover Letter (Bold)': 'Achievement-focused cover letter targeting your top employer.',
    'Cover Letter (Friendly)': 'Warm, personable cover letter for your second-choice employer.',
    'Cover Letter (Professional)': 'Traditional business cover letter for your third-choice employer.',
    'Target Employers — Battle Plan': 'Your top 50 employers ranked by fit, with approach strategies.',
    '30-Day Action Plan': 'Week-by-week job search plan with specific daily tasks.',
    'Job Application Tracker': 'Spreadsheet to track applications, follow-ups, and status.',
    'Interview Prep Sheet': 'Common questions, STAR answers, and company-specific prep.',
    'Salary Negotiation Sheet': 'Your target range, scripts, and total comp checklist.',
    'Alloy Report (Confidential)': 'Barrier strategy guide with scripts, legal rights, and resources.',
    'Online Portfolio': 'Standalone HTML portfolio page. Open in any browser.',
    'Salary Guidance': 'General salary research guidance and negotiation tips.',
  };

  let content = `================================================================
  STEEL MAN RESUMES — CAREER PACKAGE
================================================================

Generated: ${date}

================================================================
  QUICK START
================================================================

1. Open the Quick Start Guide — it tells you what to do first.
2. Review your Resume — make sure everything is accurate.
3. Read your Battle Plan (Tier 1 section) — these are your top targets.
4. Start applying. Your 30-Day Action Plan has daily tasks.

================================================================
  TABLE OF CONTENTS
================================================================

`;

  const sections = manifest?.sections || [];
  let itemNum = 0;

  for (const section of sections) {
    content += `--- ${section.title.toUpperCase()} ---\n\n`;
    for (const artifact of (section.artifacts || [])) {
      itemNum++;
      const desc = ARTIFACT_DESCRIPTIONS[artifact.display_title] || '';
      const status = artifact.status === 'pending' ? ' [generating...]' : '';
      content += `  ${String(itemNum).padStart(2, ' ')}. ${artifact.display_title}${status}\n`;
      if (desc) content += `      ${desc}\n`;
      content += '\n';
    }
  }

  content += `================================================================
  ABOUT THIS PACKAGE
================================================================

This career package was generated by Steel Man Resumes on ${date}.
Every document is customized to your specific background, skills,
and target market. No templates, no generic advice.

Questions? Contact your career coach.

================================================================
  STEEL MAN RESUMES — steelmanresumes.com
================================================================
`;

  const buffer = Buffer.from(content, 'utf-8');

  const fileName = 'README.txt';
  const objectKey = `${orgId}/${projectId}/artifacts/${runId}/${fileName}`;
  const fileObject = await uploadFile(orgId, objectKey, buffer, 'text/plain');

  const artifact = await insert<{ id: string }>('artifact', {
    org_id: orgId, run_id: runId, project_id: projectId,
    artifact_type: artifactKey, artifact_key: artifactKey, bundle_id: bundleId,
    file_object_id: fileObject.id, display_title: 'README — Table of Contents',
    display_section: 'start_here', preview_type: 'none', order_index: 0, version: 1, review_status: 'pending',
  });

  await emitEvent({
    org_id: orgId, project_id: projectId, run_id: runId, step_id: null,
    event_type: 'ARTIFACT_GENERATED', severity: 'info',
    actor_type: 'system', actor_user_id: null, actor_label: 'gen_readme',
    data_classification: 'internal', retention_class: 'standard',
    correlation_id: null, parent_event_id: null, sensitive_ref: null,
    payload: { artifact_id: artifact.id, artifact_key: artifactKey, file_name: fileName, byte_size: buffer.length },
  });

  console.log(`[gen_readme] README generated: ${fileName} (${buffer.length} bytes)`);
  return { artifactKey, fileObjectId: fileObject.id, fileName, byteSize: buffer.length };
}
